name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  github-token:
    description: 'GitHub API access token.It is used to upload test report and add comment to pull request.'
    required: true
  json-directory-path:
    description: "Path to json files directory.The images stored in this directory will be compared with the expected json files from the last upload."
    required: true
  target-hash:
    description: "The commit hash to be compared."
    required: false
  artifact-name:
    description: 'Workflow artifact name. `reg` by default.'
    required: false
  branch:
    description: 'A branch name which manages images. `reg_actions` by default.'
    required: false

# Define your outputs here.
outputs:
  result:
    description: 'ok or failed'

runs:
  using: node20
  main: dist/index.js
