name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm install
      - run: pnpm package


      - name: Install Dependencies
        id: npm-ci
        run: pnpm install --frozen-lockfile

      - name: Check Format
        id: npm-format-check
        run: pnpm run format:check

      - name: Lint
        id: npm-lint
        run: pnpm run lint

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm install
      - run: pnpm package

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          actual-directory-path: "__sample-actual__"

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.result }}"

      - name: Test Local Action(with expected)
        id: test-action-with-expected
        uses: ./
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          actual-directory-path: "__sample-actual__"
          expected-directory-path: "__sample-expected__"
          artifact-name: 'metrics-with-expected'

      - name: Print Output(with expected)
        id: output-with-expected
        run: echo "${{ steps.test-action-with-expected.outputs.result }}"
